// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _2026_MT_Komar_A_A_Lab_2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605103419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Entities.CpuModel", b =>
                {
                    b.Property<int>("CpuModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalThreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhysicalCoreCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("CpuModelId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("CpuModels");

                    b.HasData(
                        new
                        {
                            CpuModelId = 1,
                            LogicalThreadCount = 32,
                            ModelName = "AMD Ryzen 9 7950X",
                            PhysicalCoreCount = 16
                        },
                        new
                        {
                            CpuModelId = 2,
                            LogicalThreadCount = 32,
                            ModelName = "Intel Core i9-13900K",
                            PhysicalCoreCount = 24
                        },
                        new
                        {
                            CpuModelId = 3,
                            LogicalThreadCount = 12,
                            ModelName = "AMD Ryzen 5 5600X",
                            PhysicalCoreCount = 6
                        });
                });

            modelBuilder.Entity("Entities.ExecutionStatus", b =>
                {
                    b.Property<int>("ExecutionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ExecutionStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExecutionStatuses");

                    b.HasData(
                        new
                        {
                            ExecutionStatusId = 1,
                            Description = "Step completed successfully",
                            Name = "Success"
                        },
                        new
                        {
                            ExecutionStatusId = 2,
                            Description = "Step failed",
                            Name = "Failed"
                        },
                        new
                        {
                            ExecutionStatusId = 3,
                            Description = "Step was skipped",
                            Name = "Skipped"
                        },
                        new
                        {
                            ExecutionStatusId = 4,
                            Description = "Step is in progress",
                            Name = "Running"
                        });
                });

            modelBuilder.Entity("Entities.Host", b =>
                {
                    b.Property<int>("HostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CpuModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatingSystemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RamGb")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("HostId");

                    b.HasIndex("CpuModelId");

                    b.HasIndex("OperatingSystemTypeId");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("Entities.IssueCode", b =>
                {
                    b.Property<int>("IssueCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("IssueCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("IssueCodes");
                });

            modelBuilder.Entity("Entities.IssueLog", b =>
                {
                    b.Property<int>("IssueLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PipelineStepExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeverityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IssueLogId");

                    b.HasIndex("IssueCodeId");

                    b.HasIndex("PipelineStepExecutionId");

                    b.HasIndex("SeverityTypeId");

                    b.ToTable("IssueLogs");
                });

            modelBuilder.Entity("Entities.OperatingSystemType", b =>
                {
                    b.Property<int>("OperatingSystemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("OperatingSystemTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OperatingSystemTypes");

                    b.HasData(
                        new
                        {
                            OperatingSystemTypeId = 1,
                            Name = "Windows 11 Pro (64-bit)"
                        },
                        new
                        {
                            OperatingSystemTypeId = 2,
                            Name = "Windows 10 Pro (64-bit)"
                        },
                        new
                        {
                            OperatingSystemTypeId = 3,
                            Name = "Ubuntu 24.04 LTS (64-bit)"
                        },
                        new
                        {
                            OperatingSystemTypeId = 4,
                            Name = "macOS Sequoia 15"
                        });
                });

            modelBuilder.Entity("Entities.PerformanceTest", b =>
                {
                    b.Property<int>("PerformanceTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("PerformanceTestId");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("PerformanceTests");
                });

            modelBuilder.Entity("Entities.PipelineStepExecution", b =>
                {
                    b.Property<int>("PipelineStepExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PipelineStepExecutionId");

                    b.HasIndex("ExecutionStatusId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("PipelineStepExecutions");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Entities.SeverityType", b =>
                {
                    b.Property<int>("SeverityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("SeverityTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SeverityTypes");

                    b.HasData(
                        new
                        {
                            SeverityTypeId = 1,
                            Description = "Compilation or runtime error",
                            Name = "Error"
                        },
                        new
                        {
                            SeverityTypeId = 2,
                            Description = "Non-fatal issue",
                            Name = "Warning"
                        },
                        new
                        {
                            SeverityTypeId = 3,
                            Description = "Informational message",
                            Name = "Info"
                        });
                });

            modelBuilder.Entity("Entities.StageType", b =>
                {
                    b.Property<int>("StageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("StageTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StageTypes");

                    b.HasData(
                        new
                        {
                            StageTypeId = 1,
                            Name = "Build"
                        },
                        new
                        {
                            StageTypeId = 2,
                            Name = "Test"
                        },
                        new
                        {
                            StageTypeId = 3,
                            Name = "Clean"
                        },
                        new
                        {
                            StageTypeId = 4,
                            Name = "Run"
                        });
                });

            modelBuilder.Entity("Entities.ThreadSpeedMetric", b =>
                {
                    b.Property<int>("ThreadSpeedMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ParallelTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PipelineStepExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SequentialTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ThreadSpeedMetricId");

                    b.HasIndex("HostId");

                    b.HasIndex("PerformanceTestId");

                    b.HasIndex("PipelineStepExecutionId");

                    b.ToTable("ThreadSpeedMetrics");
                });

            modelBuilder.Entity("Entities.Host", b =>
                {
                    b.HasOne("Entities.CpuModel", "CpuModel")
                        .WithMany("Hosts")
                        .HasForeignKey("CpuModelId");

                    b.HasOne("Entities.OperatingSystemType", "OperatingSystemType")
                        .WithMany("Hosts")
                        .HasForeignKey("OperatingSystemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CpuModel");

                    b.Navigation("OperatingSystemType");
                });

            modelBuilder.Entity("Entities.IssueLog", b =>
                {
                    b.HasOne("Entities.IssueCode", "IssueCode")
                        .WithMany("IssueLogs")
                        .HasForeignKey("IssueCodeId");

                    b.HasOne("Entities.PipelineStepExecution", "PipelineStepExecution")
                        .WithMany("IssueLogs")
                        .HasForeignKey("PipelineStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.SeverityType", "SeverityType")
                        .WithMany("IssueLogs")
                        .HasForeignKey("SeverityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueCode");

                    b.Navigation("PipelineStepExecution");

                    b.Navigation("SeverityType");
                });

            modelBuilder.Entity("Entities.PipelineStepExecution", b =>
                {
                    b.HasOne("Entities.ExecutionStatus", "ExecutionStatus")
                        .WithMany("PipelineStepExecutions")
                        .HasForeignKey("ExecutionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Project", "Project")
                        .WithMany("PipelineStepExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.StageType", "StageType")
                        .WithMany("PipelineStepExecutions")
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionStatus");

                    b.Navigation("Project");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("Entities.ThreadSpeedMetric", b =>
                {
                    b.HasOne("Entities.Host", "Host")
                        .WithMany("ThreadSpeedMetrics")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.PerformanceTest", "PerformanceTest")
                        .WithMany("ThreadSpeedMetrics")
                        .HasForeignKey("PerformanceTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.PipelineStepExecution", "PipelineStepExecution")
                        .WithMany()
                        .HasForeignKey("PipelineStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("PerformanceTest");

                    b.Navigation("PipelineStepExecution");
                });

            modelBuilder.Entity("Entities.CpuModel", b =>
                {
                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("Entities.ExecutionStatus", b =>
                {
                    b.Navigation("PipelineStepExecutions");
                });

            modelBuilder.Entity("Entities.Host", b =>
                {
                    b.Navigation("ThreadSpeedMetrics");
                });

            modelBuilder.Entity("Entities.IssueCode", b =>
                {
                    b.Navigation("IssueLogs");
                });

            modelBuilder.Entity("Entities.OperatingSystemType", b =>
                {
                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("Entities.PerformanceTest", b =>
                {
                    b.Navigation("ThreadSpeedMetrics");
                });

            modelBuilder.Entity("Entities.PipelineStepExecution", b =>
                {
                    b.Navigation("IssueLogs");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Navigation("PipelineStepExecutions");
                });

            modelBuilder.Entity("Entities.SeverityType", b =>
                {
                    b.Navigation("IssueLogs");
                });

            modelBuilder.Entity("Entities.StageType", b =>
                {
                    b.Navigation("PipelineStepExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
