// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Data;

#nullable disable

namespace DesignTimeDbContextFactory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("MT_Ind_2.Data.Entities.CpuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogicalThreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhysicalCoreCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("CpuModels");
                });

            modelBuilder.Entity("MT_Ind_2.Data.Entities.Host", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RamGb")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CpuModelId");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.IssueLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PipelineStepExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineStepExecutionId");

                    b.ToTable("IssueLogs");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.PerformanceTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("PerformanceTests");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.PipelineStepExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalErrors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWarnings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("PipelineStepExecutions");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.StageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StageTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Build"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clean"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Run"
                        });
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.ThreadSpeedMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EfficiencyCoefficient")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ParallelTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceTestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PipelineStepExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SequentialTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("PerformanceTestId");

                    b.HasIndex("PipelineStepExecutionId");

                    b.ToTable("ThreadSpeedMetrics");
                });

            modelBuilder.Entity("MT_Ind_2.Data.Entities.Host", b =>
                {
                    b.HasOne("MT_Ind_2.Data.Entities.CpuModel", "CpuModel")
                        .WithMany("Hosts")
                        .HasForeignKey("CpuModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CpuModel");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.IssueLog", b =>
                {
                    b.HasOne("_2026_MT_Komar_A_A_Lab_2.Entities.PipelineStepExecution", "PipelineStepExecution")
                        .WithMany("IssueLogs")
                        .HasForeignKey("PipelineStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineStepExecution");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.PipelineStepExecution", b =>
                {
                    b.HasOne("_2026_MT_Komar_A_A_Lab_2.Entities.Project", "Project")
                        .WithMany("PipelineStepExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Komar_A_A_Lab_2.Entities.StageType", "StageType")
                        .WithMany("PipelineStepExecutions")
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.ThreadSpeedMetric", b =>
                {
                    b.HasOne("MT_Ind_2.Data.Entities.Host", "Host")
                        .WithMany("ThreadSpeedMetrics")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Komar_A_A_Lab_2.Entities.PerformanceTest", "PerformanceTest")
                        .WithMany("ThreadSpeedMetrics")
                        .HasForeignKey("PerformanceTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026_MT_Komar_A_A_Lab_2.Entities.PipelineStepExecution", "PipelineStepExecution")
                        .WithMany("ThreadSpeedMetrics")
                        .HasForeignKey("PipelineStepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("PerformanceTest");

                    b.Navigation("PipelineStepExecution");
                });

            modelBuilder.Entity("MT_Ind_2.Data.Entities.CpuModel", b =>
                {
                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("MT_Ind_2.Data.Entities.Host", b =>
                {
                    b.Navigation("ThreadSpeedMetrics");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.PerformanceTest", b =>
                {
                    b.Navigation("ThreadSpeedMetrics");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.PipelineStepExecution", b =>
                {
                    b.Navigation("IssueLogs");

                    b.Navigation("ThreadSpeedMetrics");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.Project", b =>
                {
                    b.Navigation("PipelineStepExecutions");
                });

            modelBuilder.Entity("_2026_MT_Komar_A_A_Lab_2.Entities.StageType", b =>
                {
                    b.Navigation("PipelineStepExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
